FILE_NOT_FOUND=BA000 - path={0}
DATA_ALREADY_EXIST=BA001 - {0}={1} {2}={3}
VALUE_IS_NULL=BA002 - {0}
NOT_FOUND_FOR=BA003 - element={0} for={1}
INVALID_MESSAGE=BB000 - msgType={0}
UNMET_CONDITION_0=BB000 - {0}
UNMET_CONDITION_1=BB001 - {0} {1}
UNMET_CONDITION_2=BB002 - {0} {1} {2} {3}
UNMET_CONDITION_3=BB003 - {0} {1} {2} {3} {4} {5}
NETWORK_FAILED=BC000 - {0}={1}
VARIABLE_LOGGING_1=BD001 - {0}={1}
VARIABLE_LOGGING_2=BD002 - {0}={1} {2}={3}
VARIABLE_LOGGING_3=BD003 - {0}={1} {2}={3} {4}={5}
VARIABLE_LOGGING_4=BD004 - {0}={1} {2}={3} {4}={5} {6}={7}
VARIABLE_LOGGING_5=BD005 - {0}={1} {2}={3} {4}={5} {6}={7} {8}={9}