FUNCTION_SUCCESS_0=DA000
FUNCTION_SUCCESS_1=DA001 - {0}={1}
FUNCTION_SUCCESS_2=DA002 - {0}={1} {2}={3}
FUNCTION_SUCCESS_3=DA003 - {0}={1} {2}={3} {4}={5}
FUNCTION_SUCCESS_4=DA004 - {0}={1} {2}={3} {4}={5} {6}={7}
FUNCTION_SUCCESS_5=DA005 - {0}={1} {2}={3} {4}={5} {6}={7} {8}={9}
FUNCTION_FAIL_0=DA006
FUNCTION_FAIL_1=DA007 - {0}={1}
FUNCTION_FAIL_2=DA008 - {0}={1} {2}={3}
FUNCTION_FAIL_3=DA009 - {0}={1} {2}={3} {4}={5}
FUNCTION_FAIL_4=DA010 - {0}={1} {2}={3} {4}={5} {6}={7}
FUNCTION_FAIL_5=DA011 - {0}={1} {2}={3} {4}={5} {6}={7} {8}={9}
FUNCTION_BRANCH_SUCCESS_0=DA012
FUNCTION_BRANCH_SUCCESS_1=DA013 - {0}={1}
FUNCTION_BRANCH_SUCCESS_2=DA014 - {0}={1} {2}={3}
FUNCTION_BRANCH_SUCCESS_3=DA015 - {0}={1} {2}={3} {4}={5}
FUNCTION_BRANCH_SUCCESS_4=DA016 - {0}={1} {2}={3} {4}={5} {6}={7}
FUNCTION_BRANCH_SUCCESS_5=DA017 - {0}={1} {2}={3} {4}={5} {6}={7} {8}={9}
FUNCTION_BRANCH_FAILED_0=DA018
FUNCTION_BRANCH_FAILED_1=DA019 - {0}={1}
FUNCTION_BRANCH_FAILED_2=DA020 - {0}={1} {2}={3}
FUNCTION_BRANCH_FAILED_3=DA021 - {0}={1} {2}={3} {4}={5}
FUNCTION_BRANCH_FAILED_4=DA022 - {0}={1} {2}={3} {4}={5} {6}={7}
FUNCTION_BRANCH_FAILED_5=DA023 - {0}={1} {2}={3} {4}={5} {6}={7} {8}={9}
VARIABLE_LOGGING_1=DB001 - {0}={1}
VARIABLE_LOGGING_2=DB002 - {0}={1} {2}={3}
VARIABLE_LOGGING_3=DB003 - {0}={1} {2}={3} {4}={5}
VARIABLE_LOGGING_4=DB004 - {0}={1} {2}={3} {4}={5} {6}={7}
VARIABLE_LOGGING_5=DB005 - {0}={1} {2}={3} {4}={5} {6}={7} {8}={9}
VARIABLE_LOGGING_6=DB006 - {0}={1} {2}={3} {4}={5} {6}={7} {8}={9} {10}={11}
VARIABLE_LOGGING_7=DB007 - {0}={1} {2}={3} {4}={5} {6}={7} {8}={9} {10}={11} {12}={13}
UNSUPPORTED_OPERATION=DC000
NO_OPERATION=DC001
