// Settings
:idprefix:
:idseparator: -
:component-name: speds-transport-library
:component: SPEDS

= {component-name}

[#summary]
== Sommaire

La *{component-name}* implémente la couche transport du protocole d'échange *{component}* utilisé pour les
communications entre les différents sous-systèmes utilisant DadaGem.

[#overview]
== Présentation

Le rôle de *{component-name}* est d'échanger des messages transport entre les sous-systèmes à partir des interfaces établies avec les couches supérieures et inférieures.
Ceci implique la création de messages transport et les réponses à ces messages.

Un service d'API est offert pour la couche supérieure.

*{component-name}* permet d'effectuer les tâches suivantes :

* Échanger des données à une autre entité.
* Recevoir des données d'une autre entité.
* Démarrer l'écoute de messages spour recevoir des messages d'autres entités de la couche transport.
* Libérer les ressources utilisées en lien avec le protocole transport lors de l’arrêt des échanges.

[#techno]
== Technologies utilisées

* Languages utilisés :
** Java

* Les API utilisés :
** speds-network-library

* Les applications tierces :
** cryptography-library

[#prerequisite]
== Préalable

Avant de débuter, il est important de s'assurer que l’ensemble des conditions suivantes soient
remplies :

* Logiciels prérequis :
** S.O.

* Composants GRIIS prérequis :
** `cryptography-library`
** `logger-library`
** `speds-network-library`


* Systèmes
** Multi-plateforme

* Matériels prérequis :
** S.O.

* Autres :
** `jsonschema2pojo`

[#build]
== Construction

Pour construire *{component-name}*, taper la commande suivante dans un
terminal :

[source, bash]
----
$ ./gradlew build
----

=== Compilation

Pour produire uniquement l'artéfact, taper la commande suivante dans un terminal :

[source, bash]
----
$ ./gradlew assemble
----

[#tests]
=== Exécution des tests

Pour exécuter les tests, taper la commande suivante dans un terminal :

[source, bash]
----
$ ./gradlew test
----

=== Installation

Pour installer l'artéfact préalablement compilé dans le dépôt local Maven, taper la commande
suivante dans un terminal :

[source, bash]
----
$ ./gradlew publishToMavenLocal
----

== Utilisation

Pour inclure *{component-name}* dans un autre projet, il faut ajouter la
dépendance dans le fichier build.gradle de ce projet, puis rafraîchir le projet Gradle. Pour plus
de renseignements, consulter la section « <<Installation>> ».

[source, gradle]
----
dependencies {
  compile "ca.griis:speds-transport-library:${version}"
}
----

*{component-name}* peut être déclarée en utilisant
`ca.griis:speds-transport-library`.

Pour développer directement sur *{component-name}*, il faut importer le
projet Gradle dans un environnement de développement intégré Java tel qu'Eclipse ou IntelliJ IDEA.
Pour plus de renseignements, consulter la section « <<Construction>> ».

=== Interface de programmation

==== Module api

*TransportClient*

|===
| Id du processus | Signature impl.                  | Comportement
| S.O.            | void listen()                    | Démarre l'écoute de messages sur le procole transport.
| S.O.            | void close()                     | Libère les ressources en lien avec le protocole transport.
| S.O.            | Boolean isPending(String msgId)  | Vérifie si la demande d’échange de données a fait l’objet d’une confirmation.
| PRO-04          | void request(String idu)         | Demande d’échange de données.
| PRO-04          | void dataRequest(String idu)     | (Obsolète) Comportement identique à `request`.
| PRO-05          | void dataConfirm()               | (Obsolète) Ne fait plus rien.
|===

*TransportServer*

|===
| Id du processus | Signature impl.               | Comportement
| S.O.            | void listen()                 | Démarre l'écoute de messages sur le procole transport.
| S.O.            | void close()                  | Libère les ressources en lien avec le protocole transport.
| PRO-11          | String indication()           | Reçoit des données.
| PRO-11          | String dataReply()            | (Obsolète) Comportement identique à `indication`.
|===

[NOTE]
====
* Le démarrage de l'écoute du message du protocole se fait automatiquement lors d'un appel `request` ou `indication`.
* La confirmation d'un accusé de réception de la couche transport  `PRO-05` est maintenant automatiquement géré par l'hôte.
* La méthode `indication` est bloquante. Tant que des données ne seront pas reçues, la méthode attendra.
* Les méthodes obsolètes seront supprimées prochainement à une autre version.
====

*Package factory*

Définit la fabrique des hôtes du protocole de *{component}*.  Un hôte permet d’être un client et un serveur sur le protocole *{component}*. La fabrique permet donc la création d’un hôte respectant des options de configuration nécessaires au bon déroulement du protocole de la couche transport.

*Options de configuration sur la version de protocole*

----
speds.tra.version   - Version du protocole de la couche transport.
speds.tra.reference - Référence du protocole de la couche transport.
----

*Options de configuration sur l'interrogateur*

L'interrogateur assure l'aiguillage des messages reçus de la couche transport en appliquant un traitement adapté à chaque type de message.

----
speds.tra.poller.maxQueueCapacity - Par défaut, la valeur est 100.

La grandeur maximale de la file bloquante de l'interrogateur où qu'on insère les données reçues.
Si la grandeur est excédée, l'ajout de données sera bloquante tant que sa capacité ne sera pas plus petite que celle définie en paramètre.

speds.tra.poller.nbThreads - Par défaut, la valeur est 1.

Le nombre de fils d'exécution sur l'interrogateur. 

speds.tra.poller.sleepMs - Par défaut, la valeur est 200.

Temps de pause sur le ou les fils d'exécution de l'interrogateur après chaque lecture de message. 
Cela permet un répis aux autres fils d'exécution, et que l'interrogateur ne monopolise pas trop le processus en cours d'exécution. 
----

[#launch]
== Démarrage

S.O.

== Documentation du code

Pour générer localement la version *française* de la documentation du code accompagnant
*{component-name}*, taper la commande suivante dans un terminal :

[source, bash]
----
./gradlew doxygenFr
----

Pour afficher la documentation du code générée, cliquer sur le fichier index.html situé dans le
dossier `build\doc-fr-doxygen\html`.

[#contact]
== Personnes ressources

* Francis Ouellet : Francis.Ouellet@usherbrooke.ca
* Jean-François Éthier : JF.Ethier@usherbrooke.ca

[#licence]
== Copyright et licences

=== Copyright

Copyright 2016-{localyear}, https://griis.ca/[GRIIS]

GRIIS (Groupe de recherche interdisciplinaire en informatique de la santé) +
Faculté des sciences et Faculté de médecine et sciences de la santé +
Université de Sherbrooke (Québec) J1K 2R1 +

CANADA

=== Licences

Le code de ce projet est sous licence link:liliqr-licence.adoc[LILIQ-R]. Click here for the
link:liliqr-licence-english.adoc[English version].

La documentation de ce projet est sous licence https://creativecommons.org/licenses/by/4.0/[CC BY 4.0].
