APP_STARTING=CA000
APP_READY=CA001
APP_PREPARING_TO_CLOSE=CA002
APP_CLOSING=CA003
COMPONENT_STARTING=CB000 - component={0}
COMPONENT_READY=CB001 - component={0}
COMPONENT_PREPARING_TO_CLOSE=CB002 - component={0}
COMPONENT_CLOSING=CB003 - component={0}
COMPONENT_STATE=CB004 - component={0} state={1}
MESSAGE_SEND=CC000 - pgaId={0} msgType={1}
MESSAGE_ANS=CC001 - pgaId={0} msgType={1}
MESSAGE_FWD=CC002 - pgaId={0} msgType={1}
MESSAGE_RECP=CC003 - pgaId={0} msgType={1}
NETWORK_MESSAGE_SEND=CC004 Sending this message - \
componentId={0} localAddress={1} source={2} sourceProxy={3} destinationProxy={4} \
destination={5} senderNumber={6} hashMessage={7} timestamp={8}
NETWORK_MESSAGE_RECP=CC005 Receiving this message - \
componentId={0} localAddress={1} source={2} sourceProxy={3} destinationProxy={4} \
destination={5} senderNumber={6} hashMessage={7} timestamp={8}
PAD_STATE=CD000 - oldState={0} newState{1}
FUNCTION_SUCCESS_0=CE000
FUNCTION_SUCCESS_1=CE001 - {0}={1}
FUNCTION_SUCCESS_2=CE002 - {0}={1} {2}={3}
FUNCTION_SUCCESS_3=CE003 - {0}={1} {2}={3} {4}={5}
FUNCTION_SUCCESS_4=CE004 - {0}={1} {2}={3} {4}={5} {6}={7}
FUNCTION_SUCCESS_5=CE005 - {0}={1} {2}={3} {4}={5} {6}={7} {8}={9}
FUNCTION_FAIL_0=CE006
FUNCTION_FAIL_1=CE007 - {0}={1}
FUNCTION_FAIL_2=CE008 - {0}={1} {2}={3}
FUNCTION_FAIL_3=CE009 - {0}={1} {2}={3} {4}={5}
FUNCTION_FAIL_4=CE010 - {0}={1} {2}={3} {4}={5} {6}={7}
FUNCTION_FAIL_5=CE011 - {0}={1} {2}={3} {4}={5} {6}={7} {8}={9}
VARIABLE_LOGGING_1=CE012 - {0}={1}
VARIABLE_LOGGING_2=CE013 - {0}={1} {2}={3}
VARIABLE_LOGGING_3=CE014 - {0}={1} {2}={3} {4}={5}
VARIABLE_LOGGING_4=CE015 - {0}={1} {2}={3} {4}={5} {6}={7}
VARIABLE_LOGGING_5=CE016 - {0}={1} {2}={3} {4}={5} {6}={7} {8}={9}
FUNCTION_START=CE017 - {0}